In [293]:
%matplotlib inline 
import numpy as np
import pandas as pd
import sklearn
!pip install mglearn
import mglearn
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [298]:
Index_data = pd.read_csv('C:/Personal/09066218/Documents/Personal/FU/Fall 2019/Practicum/Input_datawithaddressfinal.csv')
Index_data.head()


CensusTract        LAT       LONG       Index  Standardindex  \
0  48113019301  32.856345 -96.781852   74.585443      21.028506   
1  48113020600  32.872689 -96.821635   59.470157      15.824638   
2  48113019501  32.858013 -96.799359  130.542997      40.293489   
3  48113013300  32.902679 -96.793393   49.639598      12.440188   
4  48113007604  32.887345 -96.795373   72.270032      20.231360   

   CensusTract.1  Correlation_Index   \
0   4.811302e+10              70.888   
1   4.811302e+10              74.658   
2   4.811302e+10              84.482   
3   4.811301e+10              97.017   
4   4.811301e+10              71.083   

                                             Address  med_hhinc2016  \
0  3124, Bryn Mawr Drive, University Park, Dallas...       250001.0   
1  9505, Inwood Road, Meaders, Dallas, Dallas Cou...       250001.0   
2  3896, Greenbrier Drive, University Park, Dalla...       239943.0   
3  6522, Belmead Drive, Meaders, Dallas, Dallas C...       233816.0   
4  6428, Waggoner Drive, Meaders, Dallas, Dallas ...       221944.0   

   Poverty_prob_index  ...  school_poverty  student_teacher_ratio  free_lunch  \
0           88.060326  ...       95.454548              14.703566   60.344944   
1           65.228806  ...       86.956520              15.369350   74.603866   
2          119.897600  ...       74.889656              15.369350    0.000000   
3           37.544300  ...       88.970020              17.260274   24.716553   
4           44.702061  ...       47.729471              15.160703   79.800000   

   reduced_lunch  Title1_school  high_quality_ECE_centers  math.proficiency  \
0       0.479728            1.0                    1006.0         48.000000   
1       1.029837            1.0                     566.5         53.666667   
2       0.000000            0.0                    2683.5         83.000000   
3       2.721088            1.0                     461.5         84.500000   
4       1.000000            1.0                     866.0         64.000000   

   reading.proficiency  HS Graduate %  Postseceducation  
0                 34.0       0.020899          0.892372  
1                 45.0       0.048059          0.839803  
2                 80.0       0.018305          0.897627  
3                 88.5       0.061252          0.866844  
4                 54.0       0.020737          0.858986  

[5 rows x 24 columns]

In [299]:
Index_data.shape

(1175, 24)

In [300]:
Index_data.columns

Index(['CensusTract', 'LAT', 'LONG', 'Index', 'Standardindex', 'CensusTract.1',
       ' Correlation_Index ', 'Address', 'med_hhinc2016', 'Poverty_prob_index',
       'MHLTH', 'PHLTH', 'educational.attainment', 'ECE.enrolled',
       'school_poverty', 'student_teacher_ratio', 'free_lunch',
       'reduced_lunch', 'Title1_school', 'high_quality_ECE_centers',
       'math.proficiency', 'reading.proficiency', 'HS Graduate %',
       'Postseceducation'],
      dtype='object')

In [301]:
print(Index_data.isnull().sum())

CensusTract                  0
LAT                          0
LONG                         0
Index                        0
Standardindex                0
CensusTract.1               12
 Correlation_Index          12
Address                      0
med_hhinc2016                0
Poverty_prob_index           0
MHLTH                        0
PHLTH                        0
educational.attainment       0
ECE.enrolled                 0
school_poverty               0
student_teacher_ratio        0
free_lunch                   0
reduced_lunch                0
Title1_school                0
high_quality_ECE_centers     0
math.proficiency             0
reading.proficiency          0
HS Graduate %                0
Postseceducation             0
dtype: int64


In [302]:
#Index_data =Index_data.drop(columns=['HS Graduate %', 'Graduate Degree or Higher %','Bachelors Degree %'])

In [303]:
Index_data.shape

(1175, 24)

In [304]:
Index_data.columns

Index(['CensusTract', 'LAT', 'LONG', 'Index', 'Standardindex', 'CensusTract.1',
       ' Correlation_Index ', 'Address', 'med_hhinc2016', 'Poverty_prob_index',
       'MHLTH', 'PHLTH', 'educational.attainment', 'ECE.enrolled',
       'school_poverty', 'student_teacher_ratio', 'free_lunch',
       'reduced_lunch', 'Title1_school', 'high_quality_ECE_centers',
       'math.proficiency', 'reading.proficiency', 'HS Graduate %',
       'Postseceducation'],
      dtype='object')

In [305]:
# Reversed some columns by multiplying with -1 to ensure higher is better in the dataset

In [306]:
Index_data['Reverse_Poverty_prob_index'] = Index_data['Poverty_prob_index']*-1
Index_data['Reverse_MHLTH'] = Index_data['MHLTH']*-1
Index_data['Reverse_PHLTH'] = Index_data['PHLTH']*-1

In [307]:
# Drop free lunch and the unnecessary data
#Index_data =Index_data.drop(columns=['Poverty_prob_index', 'MHLTH','PHLTH']) 

In [308]:
Index_data.shape

(1175, 27)

In [309]:
Index_data.columns

Index(['CensusTract', 'LAT', 'LONG', 'Index', 'Standardindex', 'CensusTract.1',
       ' Correlation_Index ', 'Address', 'med_hhinc2016', 'Poverty_prob_index',
       'MHLTH', 'PHLTH', 'educational.attainment', 'ECE.enrolled',
       'school_poverty', 'student_teacher_ratio', 'free_lunch',
       'reduced_lunch', 'Title1_school', 'high_quality_ECE_centers',
       'math.proficiency', 'reading.proficiency', 'HS Graduate %',
       'Postseceducation', 'Reverse_Poverty_prob_index', 'Reverse_MHLTH',
       'Reverse_PHLTH'],
      dtype='object')

In [310]:
Index_datacomb=Index_data

In [311]:
# HANDLING OUTLIERS BY Z-SCORE

In [271]:
Index_datacomb.shape

(1175, 31)

In [312]:
dimcols=['CensusTract', 'LAT', 'LONG', 'Index', 'Standardindex', 'CensusTract.1',
       ' Correlation_Index ', 'Address','Poverty_prob_index',
       'MHLTH', 'PHLTH']

Index_datadim=Index_data[dimcols]

In [313]:
factcols=['educational.attainment','ECE.enrolled',
       'school_poverty','student_teacher_ratio','free_lunch',
       'reduced_lunch','Title1_school','high_quality_ECE_centers',
       'math.proficiency','reading.proficiency', 'HS Graduate %','Postseceducation',
      'med_hhinc2016','Reverse_Poverty_prob_index','Reverse_MHLTH','Reverse_PHLTH']

zfactcols=['zeducational.attainment','zECE.enrolled',
       'zschool_poverty','zstudent_teacher_ratio','zfree_lunch',
       'zreduced_lunch','zTitle1_school','zhigh_quality_ECE_centers',
       'zmath.proficiency','zreading.proficiency', 'zHS Graduate %','zPostseceducation',
      'zmed_hhinc2016','zReverse_Poverty_prob_index','zReverse_MHLTH','zReverse_PHLTH']

Index_datafact=Index_data[factcols]


In [314]:
Index_datafact.shape

(1175, 16)

In [315]:
Index_datadim.shape

(1175, 11)

In [316]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(Index_datafact))
print(z)

[[2.40444061 1.62383631 2.20605782 ... 0.96029127 1.12297748 0.9128052 ]
 [2.26156393 1.99387455 1.82750958 ... 1.00777191 1.67065491 0.5065801 ]
 [2.41993012 0.27901954 1.28998605 ... 0.89408217 1.42629189 0.0386394 ]
 ...
 [1.29781179 0.90124333 0.49845158 ... 1.23643881 2.10223404 0.77510177]
 [1.46753206 0.57454977 0.52795312 ... 0.92285329 3.10630932 2.44715834]
 [1.2926944  0.56978911 0.6744823  ... 0.7015894  3.01502975 1.02296794]]


In [317]:
threshold = 5
print(np.where(z > 5))

(array([  48,  179,  195,  199,  203,  232,  247,  872, 1067, 1083, 1101],
      dtype=int64), array([ 7,  7,  3,  7,  7,  7,  7,  3, 13, 13, 13], dtype=int64))


In [318]:
Index_datafact.shape

(1175, 16)

In [319]:
Index_datafact = Index_datafact[(z < 5).all(axis=1)]

In [320]:
Index_datafact.shape  
# 12 outliers are dropped from the dataset

(1164, 16)

In [321]:
#Z-SCORE TO SCALE THE DATA

In [322]:
Index_datafact.head()

educational.attainment  ECE.enrolled  school_poverty  \
0               89.441312     90.000000       95.454548   
1               86.204782    100.000000       86.956520   
2               89.792190     38.576779       74.889656   
3               85.294118     75.000000       88.970020   
4               89.419476     87.500000       47.729471   

   student_teacher_ratio  free_lunch  reduced_lunch  Title1_school  \
0              14.703566   60.344944       0.479728            1.0   
1              15.369350   74.603866       1.029837            1.0   
2              15.369350    0.000000       0.000000            0.0   
3              17.260274   24.716553       2.721088            1.0   
4              15.160703   79.800000       1.000000            1.0   

   high_quality_ECE_centers  math.proficiency  reading.proficiency  \
0                    1006.0         48.000000                 34.0   
1                     566.5         53.666667                 45.0   
2                    2683.5         83.000000                 80.0   
3                     461.5         84.500000                 88.5   
4                     866.0         64.000000                 54.0   

   HS Graduate %  Postseceducation  med_hhinc2016  Reverse_Poverty_prob_index  \
0       0.020899          0.892372       250001.0                  -88.060326   
1       0.048059          0.839803       250001.0                  -65.228806   
2       0.018305          0.897627       239943.0                 -119.897600   
3       0.061252          0.866844       233816.0                  -37.544300   
4       0.020737          0.858986       221944.0                  -44.702061   

   Reverse_MHLTH  Reverse_PHLTH  
0      -9.800000      -8.800000  
1      -8.000000     -10.275000  
2      -8.803125     -12.254687  
3      -7.600000     -13.800000  
4      -8.300000     -10.600000

In [323]:
from scipy.stats import zscore
#Index_datatemp =Index_data.drop(columns=['CensusTract'])
#numeric_cols = Index_datatemp.select_dtypes(include=[np.number]).columns


#Index_data1=Index_data.iloc[:,1:19].apply(zscore)
#numeric_cols
Index_datafact=Index_datafact.apply(zscore)

#Index1['CensusTract']=Index_data['CensusTract']


In [324]:
Index_datafact.shape

(1164, 16)

In [325]:
Index_datafact.head()

educational.attainment  ECE.enrolled  school_poverty  \
0                2.405598      1.624040        2.203311   
1                2.262687      1.993367        1.825229   
2                2.421091     -0.275160        1.288367   
3                2.222476      1.070049        1.914810   
4                2.404634      1.531708        0.079996   

   student_teacher_ratio  free_lunch  reduced_lunch  Title1_school  \
0              -0.217025    0.252343      -1.439436       0.526330   
1               0.117217    0.779920      -1.294296       0.526330   
2               0.117217   -1.980410      -1.566006      -2.279653   
3               1.066514   -1.065902      -0.848080       0.526330   
4               0.012470    0.972177      -1.302168       0.526330   

   high_quality_ECE_centers  math.proficiency  reading.proficiency  \
0                 -0.429733         -0.061857            -0.811109   
1                 -0.983843          0.300119            -0.109663   
2                  1.685214          2.173877             2.122213   
3                 -1.116224          2.269694             2.664240   
4                 -0.606241          0.960193             0.464248   

   HS Graduate %  Postseceducation  med_hhinc2016  Reverse_Poverty_prob_index  \
0      -2.002988          2.442676       4.959555                    0.982971   
1      -1.722146          2.208588       4.959555                    1.032080   
2      -2.029806          2.466077       4.686127                    0.914492   
3      -1.585734          2.329002       4.519564                    1.091627   
4      -2.004656          2.294011       4.196822                    1.076232   

   Reverse_MHLTH  Reverse_PHLTH  
0       1.127410       0.919405  
1       1.677346       0.513001  
2       1.431975      -0.032459  
3       1.799554      -0.458236  
4       1.585690       0.423454

In [326]:
Index_datacomb.shape

(1175, 27)

In [327]:
for col in factcols:
    col_zscore = col + '_zscore'
    Index_datacomb[col_zscore] = (Index_datacomb[col] - Index_datacomb[col].mean())/Index_datacomb[col].std(ddof=0)


In [329]:
Index_datacomb.shape

(1175, 43)

In [332]:
Index_datacomb

CensusTract        LAT       LONG       Index  Standardindex  \
0     48113019301  32.856345 -96.781852   74.585443      21.028506   
1     48113020600  32.872689 -96.821635   59.470157      15.824638   
2     48113019501  32.858013 -96.799359  130.542997      40.293489   
3     48113013300  32.902679 -96.793393   49.639598      12.440188   
4     48113007604  32.887345 -96.795373   72.270032      20.231360   
5     48113019700  32.832828 -96.796792   49.640724      12.440575   
6     48113007301  32.859501 -96.813724   50.263627      12.655028   
7     48085031706  32.993013 -96.820978   48.203955      11.945927   
8     48121021626  33.075424 -96.848332   51.383220      13.040479   
9     48439113909  32.934332 -97.138230  121.074708      37.033760   
10    48439113908  32.934228 -97.171727  101.005976      30.124527   
11    48113013500  32.902392 -96.828527   60.491618      16.176305   
12    48439113906  32.958548 -97.170477  106.099916      31.878261   
13    48113019302  32.844638 -96.780477   65.827734      18.013415   
14    48439113907  32.968469 -97.137686  114.758082      34.859082   
15    48113019800  32.829484 -96.810010   75.822459      21.454384   
16    48121021749  33.055019 -97.101904   71.178520      19.855576   
17    48439113815  32.913783 -97.204370   97.188801      28.810356   
18    48113019600  32.831427 -96.787641   59.184365      15.726246   
19    48085030302  33.239775 -96.744746   57.164019      15.030684   
20    48085030407  33.127492 -96.834086   71.852289      20.087540   
21    48439113910  32.965467 -97.219330  116.271814      35.380227   
22    48439113634  32.895858 -97.135174   77.728812      22.110700   
23    48121021751  33.028140 -97.098377  101.784897      30.392693   
24    48113019502  32.844610 -96.806328   81.965900      23.569439   
25    48113013400  32.902116 -96.811385   54.499251      14.113262   
26    48439113622  32.877326 -97.132483   74.589549      21.029919   
27    48121021753  33.005262 -97.085788   84.266382      24.361445   
28    48121021512  33.115634 -97.101618   76.567178      21.710775   
29    48121021900  33.127645 -96.855105   92.131377      27.069194   
...           ...        ...        ...         ...            ...   
1145  48113010804  32.713264 -96.862679   81.917530      23.552786   
1146  48439123100  32.738598 -97.308695   50.889039      12.870344   
1147  48113008704  32.695158 -96.781475   50.957661      12.893969   
1148  48439103702  32.723373 -97.263465   56.525307      14.810790   
1149  48113008603  32.735834 -96.772610   33.143822       6.761047   
1150  48113012208  32.799710 -96.722191   45.533445      11.026528   
1151  48113016605  32.636631 -96.848248  107.526806      32.369509   
1152  48113008802  32.710290 -96.787507   80.449254      23.047290   
1153  48113004900  32.736570 -96.805117   63.218869      17.115239   
1154  48439106102  32.676603 -97.251037   63.434183      17.189367   
1155  48113014204  32.845886 -96.923438   38.979750       8.770231   
1156  48439106516  32.765436 -97.221901   68.196072      18.828783   
1157  48121021000  33.205573 -97.146864   46.575446      11.385266   
1158  48113001503  32.802911 -96.776955   55.409571      14.426666   
1159  48113004000  32.745960 -96.766426   21.168297       2.638131   
1160  48113020300  32.774300 -96.766809   35.321242       7.510686   
1161  48113019213  32.936534 -96.754721   53.683607      13.832453   
1162  48439122300  32.732972 -97.109845   34.054265       7.074493   
1163  48121020900  33.202101 -97.158432   34.824187       7.339560   
1164  48113008701  32.700892 -96.764032   71.756708      20.054633   
1165  48113003901  32.759903 -96.745182   36.450091       7.899324   
1166  48439102500  32.721682 -97.404422   49.968981      12.553587   
1167  48113009304  32.717173 -96.699697  113.780748      34.522607   
1168  48113008604  32.717415 -96.770074   50.898869      12.873728   
1169  48113002701  32.773837 -96.739615   51.269583      13.001357   
1170  4811302050

In [333]:
Index_datacomb.to_csv('C:/Personal/09066218/Documents/Personal/FU/Fall 2019/Practicum/OutputwithZvalues.csv', index=True)  

In [334]:
Index_datafact.to_csv('C:/Personal/09066218/Documents/Personal/FU/Fall 2019/Practicum/Input_Zvaluesforreg.csv', index=True) 